---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    ecs:
      ansible_ssh_user: "ubuntu"
      # ansible_host: FILL
      ansible_private_key_file: "~/.ssh/privateKey.pem"