---
all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"
    ecs:
      ansible_ssh_user: "ubuntu"
      ansible_host: 80.158.7.172
